import type { ProblemId } from '../src/engine/types';

export const advancedCases: [ProblemId, unknown, unknown][] = [
  ['construct-binary-tree-from-preorder-and-inorder-traversal', { preorder: [3, 9, 20, 15, 7], inorder: [9, 3, 15, 20, 7] }, [3, 9, 20, null, null, 15, 7]],
  ['construct-binary-tree-from-preorder-and-inorder-traversal', { preorder: [], inorder: [] }, []],
  ['construct-binary-tree-from-preorder-and-inorder-traversal', { preorder: [0], inorder: [0] }, [0]],
  ['construct-binary-tree-from-preorder-and-inorder-traversal', { preorder: [1, 2, 3], inorder: [3, 2, 1] }, [1, 2, null, 3]],
  ['construct-binary-tree-from-preorder-and-inorder-traversal', { preorder: [1, 2, 3], inorder: [1, 3, 2] }, [1, null, 2, 3]],
  ['construct-binary-tree-from-preorder-and-inorder-traversal', { preorder: [0, -10000, 10000], inorder: [-10000, 0, 10000] }, [0, -10000, 10000]],
  ['path-sum-iii', { tree: [10, 5, -3, 3, 2, null, 11, 3, -2, null, 1], targetSum: 8 }, 3],
  ['path-sum-iii', { tree: [], targetSum: 0 }, 0],
  ['path-sum-iii', { tree: [0], targetSum: 0 }, 1],
  ['path-sum-iii', { tree: [0, 0, 0, 0, 0, 0, 0], targetSum: 0 }, 17],
  ['path-sum-iii', { tree: [1, -1, -1], targetSum: 0 }, 2],
  ['path-sum-iii', { tree: [1, 2, 3], targetSum: 99 }, 0],
  ['lowest-common-ancestor-of-a-binary-tree', { tree: [3, 5, 1, 6, 2, 0, 8, null, null, 7, 4], p: 1, q: 8 }, { id: 1, value: 5 }],
  ['lowest-common-ancestor-of-a-binary-tree', { tree: [1], p: 0, q: 0 }, { id: 0, value: 1 }],
  ['lowest-common-ancestor-of-a-binary-tree', { tree: [1, 1, 1], p: 1, q: 2 }, { id: 0, value: 1 }],
  ['lowest-common-ancestor-of-a-binary-tree', { tree: [1, null, 2, 3], p: 1, q: 2 }, { id: 1, value: 2 }],
  ['lowest-common-ancestor-of-a-binary-tree', { tree: [1, 2, 3], p: 2, q: 2 }, { id: 2, value: 3 }],
  ['lowest-common-ancestor-of-a-binary-tree', { tree: [1, 2, 3, 4, 5], p: 3, q: 4 }, { id: 1, value: 2 }],
  ['binary-tree-maximum-path-sum', { tree: [-10, 9, 20, null, null, 15, 7] }, 42],
  ['binary-tree-maximum-path-sum', { tree: [-3] }, -3],
  ['binary-tree-maximum-path-sum', { tree: [-5, -2, -8] }, -2],
  ['binary-tree-maximum-path-sum', { tree: [0, 0, 0] }, 0],
  ['binary-tree-maximum-path-sum', { tree: [1, 2, 3] }, 6],
  ['binary-tree-maximum-path-sum', { tree: [10000, null, 10000, null, 10000] }, 30000],
  ['sort-list', { values: [4, 2, 1, 3] }, [1, 2, 3, 4]],
  ['sort-list', { values: [] }, []],
  ['sort-list', { values: [0] }, [0]],
  ['sort-list', { values: [2, 1, 2, 1] }, [1, 1, 2, 2]],
  ['sort-list', { values: [3, 2, 1] }, [1, 2, 3]],
  ['sort-list', { values: [10000, -10000, 0] }, [-10000, 0, 10000]],
  ['merge-k-sorted-lists', { lists: [[1, 4, 5], [1, 3, 4], [2, 6]] }, [1, 1, 2, 3, 4, 4, 5, 6]],
  ['merge-k-sorted-lists', { lists: [] }, []],
  ['merge-k-sorted-lists', { lists: [[], [], []] }, []],
  ['merge-k-sorted-lists', { lists: [[-1, 0, 0]] }, [-1, 0, 0]],
  ['merge-k-sorted-lists', { lists: [[1, 1], [1], [], [1, 2]] }, [1, 1, 1, 1, 2]],
  ['merge-k-sorted-lists', { lists: [[], [-10000], [10000]] }, [-10000, 10000]],
  ['lru-cache', { capacity: 2, operations: [{ op: 'put', key: 1, value: 1 }, { op: 'put', key: 2, value: 2 }, { op: 'get', key: 1 }, { op: 'put', key: 3, value: 3 }, { op: 'get', key: 2 }, { op: 'get', key: 3 }] }, [null, null, 1, null, -1, 3]],
  ['lru-cache', { capacity: 1, operations: [] }, []],
  ['lru-cache', { capacity: 1, operations: [{ op: 'get', key: 0 }] }, [-1]],
  ['lru-cache', { capacity: 1, operations: [{ op: 'put', key: 1, value: 2 }, { op: 'put', key: 1, value: 3 }, { op: 'get', key: 1 }] }, [null, null, 3]],
  ['lru-cache', { capacity: 1, operations: [{ op: 'put', key: -1, value: -1 }, { op: 'get', key: -1 }, { op: 'put', key: 0, value: 0 }, { op: 'get', key: -1 }, { op: 'get', key: 0 }] }, [null, -1, null, -1, 0]],
  ['lru-cache', { capacity: 2, operations: [{ op: 'put', key: 1, value: 1 }, { op: 'put', key: 2, value: 2 }, { op: 'put', key: 1, value: 9 }, { op: 'put', key: 3, value: 3 }, { op: 'get', key: 2 }, { op: 'get', key: 1 }] }, [null, null, null, null, -1, 9]],
  ['permutations', { nums: [1, 2, 3] }, [[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]],
  ['permutations', { nums: [] }, [[]]],
  ['permutations', { nums: [0] }, [[0]]],
  ['permutations', { nums: [2, 1] }, [[2, 1], [1, 2]]],
  ['permutations', { nums: [-10000, 10000] }, [[-10000, 10000], [10000, -10000]]],
  ['permutations', { nums: [-1, 0] }, [[-1, 0], [0, -1]]],
  ['subsets', { nums: [1, 2, 3] }, [[], [1], [1, 2], [1, 2, 3], [1, 3], [2], [2, 3], [3]]],
  ['subsets', { nums: [] }, [[]]],
  ['subsets', { nums: [0] }, [[], [0]]],
  ['subsets', { nums: [2, 1] }, [[], [2], [2, 1], [1]]],
  ['subsets', { nums: [-10000, 10000] }, [[], [-10000], [-10000, 10000], [10000]]],
  ['subsets', { nums: [-1, 0] }, [[], [-1], [-1, 0], [0]]],
  ['combination-sum', { candidates: [2, 3, 6, 7], target: 7 }, [[2, 2, 3], [7]]],
  ['combination-sum', { candidates: [], target: 0 }, [[]]],
  ['combination-sum', { candidates: [], target: 1 }, []],
  ['combination-sum', { candidates: [2], target: 3 }, []],
  ['combination-sum', { candidates: [3, 2], target: 6 }, [[2, 2, 2], [3, 3]]],
  ['combination-sum', { candidates: [1], target: 10 }, [Array(10).fill(1)]],
];
