import type { DPGreedyId } from '../src/engine/presets/dp-greedy';

export const dpGreedyCases: [DPGreedyId, unknown, unknown][] = [
  ['jump-game-ii', { nums: [2,3,1,1,4] }, 2],
  ['jump-game-ii', { nums: [0] }, 0],
  ['jump-game-ii', { nums: [0,1] }, -1],
  ['jump-game-ii', { nums: [3,2,1,0,4] }, -1],
  ['jump-game-ii', { nums: [1,1,1,1] }, 3],
  ['jump-game-ii', { nums: [24,0,0] }, 1],
  ['partition-labels', { s: 'ababcbacadefegdehijhklij' }, [9,7,8]],
  ['partition-labels', { s: '' }, []],
  ['partition-labels', { s: 'a' }, [1]],
  ['partition-labels', { s: 'aaaa' }, [4]],
  ['partition-labels', { s: 'abc' }, [1,1,1]],
  ['partition-labels', { s: 'eccbbbbdec' }, [10]],
  ['pascals-triangle', { numRows: 0 }, []],
  ['pascals-triangle', { numRows: 1 }, [[1]]],
  ['pascals-triangle', { numRows: 2 }, [[1],[1,1]]],
  ['pascals-triangle', { numRows: 3 }, [[1],[1,1],[1,2,1]]],
  ['pascals-triangle', { numRows: 4 }, [[1],[1,1],[1,2,1],[1,3,3,1]]],
  ['pascals-triangle', { numRows: 5 }, [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]],
  ['house-robber', { nums: [2,7,9,3,1] }, 12],
  ['house-robber', { nums: [] }, 0],
  ['house-robber', { nums: [9] }, 9],
  ['house-robber', { nums: [2,1] }, 2],
  ['house-robber', { nums: [0,0,0] }, 0],
  ['house-robber', { nums: [2,1,1,2] }, 4],
  ['perfect-squares', { n: 0 }, 0],
  ['perfect-squares', { n: 1 }, 1],
  ['perfect-squares', { n: 12 }, 3],
  ['perfect-squares', { n: 13 }, 2],
  ['perfect-squares', { n: 7 }, 4],
  ['perfect-squares', { n: 40 }, 2],
  ['word-break', { s: 'leetcode', wordDict: ['leet','code'] }, true],
  ['word-break', { s: '', wordDict: [] }, true],
  ['word-break', { s: 'a', wordDict: [] }, false],
  ['word-break', { s: 'applepenapple', wordDict: ['apple','pen'] }, true],
  ['word-break', { s: 'catsandog', wordDict: ['cats','dog','sand','and','cat'] }, false],
  ['word-break', { s: 'ab', wordDict: ['b'] }, false],
  ['maximum-product-subarray', { nums: [-2,3,-4] }, 24],
  ['maximum-product-subarray', { nums: [2,3,-2,4] }, 6],
  ['maximum-product-subarray', { nums: [-2] }, -2],
  ['maximum-product-subarray', { nums: [-2,0,-1] }, 0],
  ['maximum-product-subarray', { nums: [0,-1] }, 0],
  ['maximum-product-subarray', { nums: Array(12).fill(5) }, 244140625],
  ['partition-equal-subset-sum', { nums: [1,5,11,5] }, true],
  ['partition-equal-subset-sum', { nums: [1,2,3,5] }, false],
  ['partition-equal-subset-sum', { nums: [1] }, false],
  ['partition-equal-subset-sum', { nums: [2] }, false],
  ['partition-equal-subset-sum', { nums: [1,1] }, true],
  ['partition-equal-subset-sum', { nums: [1,2,5] }, false],
  ['unique-paths', { m: 3, n: 4 }, 10],
  ['unique-paths', { m: 1, n: 1 }, 1],
  ['unique-paths', { m: 1, n: 6 }, 1],
  ['unique-paths', { m: 6, n: 1 }, 1],
  ['unique-paths', { m: 2, n: 2 }, 2],
  ['unique-paths', { m: 6, n: 6 }, 252],
  ['minimum-path-sum', { grid: [[1,3,1],[1,5,1],[4,2,1]] }, 7],
  ['minimum-path-sum', { grid: [[5]] }, 5],
  ['minimum-path-sum', { grid: [[0,0],[0,0]] }, 0],
  ['minimum-path-sum', { grid: [[1,2,3]] }, 6],
  ['minimum-path-sum', { grid: [[1],[2],[3]] }, 6],
  ['minimum-path-sum', { grid: [[1,9,1],[1,1,1]] }, 4],
];

export const dpGreedyMaximums: [DPGreedyId, unknown][] = [
  ['jump-game-ii', { nums: Array(24).fill(1) }],
  ['partition-labels', { s: 'abcdefghijklmnopqrstuvwx' }],
  ['pascals-triangle', { numRows: 10 }],
  ['house-robber', { nums: Array(16).fill(100) }],
  ['perfect-squares', { n: 40 }],
  ['word-break', { s: 'aaaaaaaaaaaaab', wordDict: ['a','aa','aaa','aaaa','aaaaa','aaaaaa','aaaaaaa','aaaaaaaa'] }],
  ['maximum-product-subarray', { nums: Array(12).fill(-5) }],
  ['partition-equal-subset-sum', { nums: Array(12).fill(5) }],
  ['unique-paths', { m: 6, n: 6 }],
  ['minimum-path-sum', { grid: Array.from({ length: 6 }, () => Array(6).fill(100)) }],
];
