import type { ProblemId } from '../src/engine/types';

const boards = (columns: number[][]) => columns.map((cols) => cols.map((col) => '.'.repeat(col) + 'Q' + '.'.repeat(cols.length - col - 1)));
export const explorationCases: [ProblemId, unknown, unknown][] = [
  ['letter-combinations-of-a-phone-number', { digits: '23' }, ['ad', 'ae', 'af', 'bd', 'be', 'bf', 'cd', 'ce', 'cf']],
  ['letter-combinations-of-a-phone-number', { digits: '' }, []],
  ['letter-combinations-of-a-phone-number', { digits: '2' }, ['a', 'b', 'c']],
  ['letter-combinations-of-a-phone-number', { digits: '7' }, ['p', 'q', 'r', 's']],
  ['letter-combinations-of-a-phone-number', { digits: '9' }, ['w', 'x', 'y', 'z']],
  ['letter-combinations-of-a-phone-number', { digits: '22' }, ['aa', 'ab', 'ac', 'ba', 'bb', 'bc', 'ca', 'cb', 'cc']],
  ['letter-combinations-of-a-phone-number', { digits: '8' }, ['t', 'u', 'v']],
  ['generate-parentheses', { n: 0 }, ['']],
  ['generate-parentheses', { n: 1 }, ['()']],
  ['generate-parentheses', { n: 2 }, ['(())', '()()']],
  ['generate-parentheses', { n: 3 }, ['((()))', '(()())', '(())()', '()(())', '()()()']],
  ['generate-parentheses', { n: 4 }, ['(((())))', '((()()))', '((())())', '((()))()', '(()(()))', '(()()())', '(()())()', '(())(())', '(())()()', '()((()))', '()(()())', '()(())()', '()()(())', '()()()()']],
  ['palindrome-partitioning', { s: 'aab' }, [['a', 'a', 'b'], ['aa', 'b']]],
  ['palindrome-partitioning', { s: '' }, [[]]],
  ['palindrome-partitioning', { s: 'a' }, [['a']]],
  ['palindrome-partitioning', { s: 'abc' }, [['a', 'b', 'c']]],
  ['palindrome-partitioning', { s: 'aaa' }, [['a', 'a', 'a'], ['a', 'aa'], ['aa', 'a'], ['aaa']]],
  ['palindrome-partitioning', { s: 'Aa' }, [['A', 'a']]],
  ['word-search', { board: [['A', 'B', 'C'], ['S', 'F', 'C'], ['A', 'D', 'E']], word: 'ABCC' }, true],
  ['word-search', { board: [['A', 'B'], ['C', 'D']], word: 'ABA' }, false],
  ['word-search', { board: [['A', 'B'], ['C', 'D']], word: 'AD' }, false],
  ['word-search', { board: [], word: '' }, true],
  ['word-search', { board: [], word: 'A' }, false],
  ['word-search', { board: [['A']], word: 'A' }, true],
  ['word-search', { board: [['A']], word: 'a' }, false],
  ['n-queens', { n: 1 }, [['Q']]],
  ['n-queens', { n: 2 }, []],
  ['n-queens', { n: 3 }, []],
  ['n-queens', { n: 4 }, boards([[1, 3, 0, 2], [2, 0, 3, 1]])],
  ['n-queens', { n: 5 }, boards([[0,2,4,1,3], [0,3,1,4,2], [1,3,0,2,4], [1,4,2,0,3], [2,0,3,1,4], [2,4,1,3,0], [3,0,2,4,1], [3,1,4,2,0], [4,1,3,0,2], [4,2,0,3,1]])],
  ['number-of-islands', { grid: [[1, 1, 0, 0], [1, 0, 0, 1], [0, 0, 1, 1]] }, 2],
  ['number-of-islands', { grid: [] }, 0],
  ['number-of-islands', { grid: [[0]] }, 0],
  ['number-of-islands', { grid: [[1]] }, 1],
  ['number-of-islands', { grid: [[1, 0], [0, 1]] }, 2],
  ['number-of-islands', { grid: [[1, 1], [1, 1]] }, 1],
  ['rotting-oranges', { grid: [[2, 1, 1], [1, 1, 0], [0, 1, 1]] }, 4],
  ['rotting-oranges', { grid: [] }, 0],
  ['rotting-oranges', { grid: [[1]] }, -1],
  ['rotting-oranges', { grid: [[0, 2]] }, 0],
  ['rotting-oranges', { grid: [[2, 1, 1, 1, 2]] }, 2],
  ['rotting-oranges', { grid: [[2, 1, 1], [0, 1, 1], [1, 0, 1]] }, -1],
  ['course-schedule', { numCourses: 4, prerequisites: [[1,0],[2,0],[3,1],[3,2]] }, true],
  ['course-schedule', { numCourses: 0, prerequisites: [] }, true],
  ['course-schedule', { numCourses: 1, prerequisites: [[0,0]] }, false],
  ['course-schedule', { numCourses: 2, prerequisites: [[1,0],[0,1]] }, false],
  ['course-schedule', { numCourses: 4, prerequisites: [[1,0],[0,1],[2,1]] }, false],
  ['course-schedule', { numCourses: 3, prerequisites: [] }, true],
  ['spiral-matrix', { matrix: [[1,2,3],[4,5,6],[7,8,9]] }, [1,2,3,6,9,8,7,4,5]],
  ['spiral-matrix', { matrix: [] }, []],
  ['spiral-matrix', { matrix: [[1,2,3,4]] }, [1,2,3,4]],
  ['spiral-matrix', { matrix: [[1],[2],[3],[4]] }, [1,2,3,4]],
  ['spiral-matrix', { matrix: [[-10000,0],[10000,0]] }, [-10000,0,0,10000]],
  ['spiral-matrix', { matrix: [[1,2,3],[4,5,6]] }, [1,2,3,6,5,4]],
  ['set-matrix-zeroes', { matrix: [[1,1,1],[1,0,1],[1,1,1]] }, [[1,0,1],[0,0,0],[1,0,1]]],
  ['set-matrix-zeroes', { matrix: [] }, []],
  ['set-matrix-zeroes', { matrix: [[0,2,3],[4,5,6]] }, [[0,0,0],[0,5,6]]],
  ['set-matrix-zeroes', { matrix: [[1,0,3],[4,5,6]] }, [[0,0,0],[4,0,6]]],
  ['set-matrix-zeroes', { matrix: [[1,2],[0,3],[4,5]] }, [[0,2],[0,0],[0,5]]],
  ['set-matrix-zeroes', { matrix: [[-10000,10000]] }, [[-10000,10000]]],
];
