import type { FinalSixId } from '../src/engine/presets/final-six';
export const finalSixCases: [FinalSixId, unknown, unknown][] = [
  ['longest-palindromic-substring', { s: 'babad' }, 'bab'],
  ['longest-palindromic-substring', { s: 'cbbd' }, 'bb'],
  ['longest-palindromic-substring', { s: '' }, ''],
  ['longest-palindromic-substring', { s: 'a' }, 'a'],
  ['longest-palindromic-substring', { s: 'aaaa' }, 'aaaa'],
  ['longest-palindromic-substring', { s: 'ac' }, 'a'],
  ['longest-common-subsequence', { text1: 'abcde', text2: 'ace' }, 3],
  ['longest-common-subsequence', { text1: '', text2: '' }, 0],
  ['longest-common-subsequence', { text1: 'abc', text2: '' }, 0],
  ['longest-common-subsequence', { text1: 'abc', text2: 'def' }, 0],
  ['longest-common-subsequence', { text1: 'aaa', text2: 'aa' }, 2],
  ['longest-common-subsequence', { text1: 'abc', text2: 'bac' }, 2],
  ['edit-distance', { word1: 'horse', word2: 'ros' }, 3],
  ['edit-distance', { word1: '', word2: '' }, 0],
  ['edit-distance', { word1: '', word2: 'abc' }, 3],
  ['edit-distance', { word1: 'abc', word2: '' }, 3],
  ['edit-distance', { word1: 'same', word2: 'same' }, 0],
  ['edit-distance', { word1: 'ab', word2: 'ba' }, 2],
  ['single-number', { nums: [4,1,2,1,2] }, 4],
  ['single-number', { nums: [0] }, 0],
  ['single-number', { nums: [-128,127,127] }, -128],
  ['single-number', { nums: [-1,0,-1] }, 0],
  ['single-number', { nums: [-5,-5,7] }, 7],
  ['single-number', { nums: [2,2,1] }, 1],
  ['majority-element', { nums: [2,2,1,1,1,2,2] }, 2],
  ['majority-element', { nums: [0] }, 0],
  ['majority-element', { nums: [-1,-1,2] }, -1],
  ['majority-element', { nums: [1,2,2] }, 2],
  ['majority-element', { nums: [1,1] }, 1],
  ['majority-element', { nums: [2,1,2,1,2,2] }, 2],
  ['find-the-duplicate-number', { nums: [1,3,4,2,2] }, 2],
  ['find-the-duplicate-number', { nums: [3,1,3,4,2] }, 3],
  ['find-the-duplicate-number', { nums: [1,1] }, 1],
  ['find-the-duplicate-number', { nums: [2,2,2,2,2] }, 2],
  ['find-the-duplicate-number', { nums: [1,2,3,4,5,5] }, 5],
  ['find-the-duplicate-number', { nums: [2,1,2] }, 2],
];
export const finalSixMaximums: [FinalSixId, unknown][] = [
  ['longest-palindromic-substring', { s: 'a'.repeat(16) }],
  ['longest-common-subsequence', { text1: 'abcdefgh', text2: 'hgfedcba' }],
  ['edit-distance', { word1: 'aaaaaaaa', word2: 'bbbbbbbb' }],
  ['single-number', { nums: [...Array.from({ length: 11 }, (_, i) => i - 5),127,...Array.from({ length: 11 }, (_, i) => i - 5)] }],
  ['majority-element', { nums: [...Array(11).fill(-10000),...Array(13).fill(10000)] }],
  ['find-the-duplicate-number', { nums: [1,2,3,4,5,6,7,8,9,10,11,12,12] }],
];
