import type { ProblemId } from '../src/engine/types';

export const linkedListCases: [ProblemId, unknown, unknown][] = [
  ['intersection-of-two-linked-lists', { prefixA: [4, 1], prefixB: [5, 6, 1], shared: [8, 4, 5] }, { indexA: 2, indexB: 3, value: 8 }],
  ['intersection-of-two-linked-lists', { prefixA: [1], prefixB: [1], shared: [] }, null],
  ['intersection-of-two-linked-lists', { prefixA: [], prefixB: [4], shared: [8, 9] }, { indexA: 0, indexB: 1, value: 8 }],
  ['intersection-of-two-linked-lists', { prefixA: [2], prefixB: [], shared: [8] }, { indexA: 1, indexB: 0, value: 8 }],
  ['intersection-of-two-linked-lists', { prefixA: [], prefixB: [], shared: [] }, null],
  ['intersection-of-two-linked-lists', { prefixA: [], prefixB: [], shared: [0] }, { indexA: 0, indexB: 0, value: 0 }],
  ['intersection-of-two-linked-lists', { prefixA: [-1, -1], prefixB: [-1], shared: [-1] }, { indexA: 2, indexB: 1, value: -1 }],
  ['palindrome-linked-list', { values: [1, 2, 2, 1] }, true],
  ['palindrome-linked-list', { values: [] }, true],
  ['palindrome-linked-list', { values: [2] }, true],
  ['palindrome-linked-list', { values: [1, 2] }, false],
  ['palindrome-linked-list', { values: [1, 2, 1] }, true],
  ['palindrome-linked-list', { values: [1, 2, 3, 1] }, false],
  ['palindrome-linked-list', { values: [0, 0, 0] }, true],
  ['linked-list-cycle', { values: [3, 2, 0, -4], pos: 1 }, true],
  ['linked-list-cycle', { values: [], pos: -1 }, false],
  ['linked-list-cycle', { values: [1], pos: -1 }, false],
  ['linked-list-cycle', { values: [1], pos: 0 }, true],
  ['linked-list-cycle', { values: [2, 2, 2], pos: -1 }, false],
  ['linked-list-cycle', { values: [1, 2], pos: 0 }, true],
  ['linked-list-cycle', { values: [1, 2, 3, 4, 5], pos: 3 }, true],
  ['linked-list-cycle-ii', { values: [3, 2, 0, -4], pos: 1 }, 1],
  ['linked-list-cycle-ii', { values: [], pos: -1 }, null],
  ['linked-list-cycle-ii', { values: [1], pos: -1 }, null],
  ['linked-list-cycle-ii', { values: [1], pos: 0 }, 0],
  ['linked-list-cycle-ii', { values: [2, 2, 2], pos: -1 }, null],
  ['linked-list-cycle-ii', { values: [1, 2], pos: 0 }, 0],
  ['linked-list-cycle-ii', { values: [1, 2, 3, 4, 5], pos: 3 }, 3],
  ['merge-two-sorted-lists', { a: [1, 2, 4], b: [1, 3, 4] }, [1, 1, 2, 3, 4, 4]],
  ['merge-two-sorted-lists', { a: [], b: [] }, []],
  ['merge-two-sorted-lists', { a: [], b: [1, 2] }, [1, 2]],
  ['merge-two-sorted-lists', { a: [1, 1], b: [1, 1] }, [1, 1, 1, 1]],
  ['merge-two-sorted-lists', { a: [-5, -1, 0], b: [-4, -1, 3] }, [-5, -4, -1, -1, 0, 3]],
  ['merge-two-sorted-lists', { a: [-10000, 10000], b: [] }, [-10000, 10000]],
  ['add-two-numbers', { a: [2, 4, 3], b: [5, 6, 4] }, [7, 0, 8]],
  ['add-two-numbers', { a: [0], b: [0] }, [0]],
  ['add-two-numbers', { a: [9], b: [1] }, [0, 1]],
  ['add-two-numbers', { a: [9, 9, 9], b: [1] }, [0, 0, 0, 1]],
  ['add-two-numbers', { a: [1], b: [9, 9, 9] }, [0, 0, 0, 1]],
  ['add-two-numbers', { a: [9, 9, 9, 9, 9, 9, 9, 9], b: [1] }, [0, 0, 0, 0, 0, 0, 0, 0, 1]],
  ['add-two-numbers', { a: [8, 1], b: [0] }, [8, 1]],
  ['remove-nth-node-from-end-of-list', { values: [1, 2, 3, 4, 5], n: 2 }, [1, 2, 3, 5]],
  ['remove-nth-node-from-end-of-list', { values: [9], n: 1 }, []],
  ['remove-nth-node-from-end-of-list', { values: [1, 2, 3], n: 3 }, [2, 3]],
  ['remove-nth-node-from-end-of-list', { values: [1, 2, 3], n: 1 }, [1, 2]],
  ['remove-nth-node-from-end-of-list', { values: [1, 1, 1], n: 2 }, [1, 1]],
  ['remove-nth-node-from-end-of-list', { values: [-10000, 10000], n: 1 }, [-10000]],
  ['swap-nodes-in-pairs', { values: [1, 2, 3, 4, 5] }, [2, 1, 4, 3, 5]],
  ['swap-nodes-in-pairs', { values: [] }, []],
  ['swap-nodes-in-pairs', { values: [1] }, [1]],
  ['swap-nodes-in-pairs', { values: [7, 7] }, [7, 7]],
  ['swap-nodes-in-pairs', { values: [0, -1, -2] }, [-1, 0, -2]],
  ['swap-nodes-in-pairs', { values: [1, 2, 3, 4, 5, 6] }, [2, 1, 4, 3, 6, 5]],
  ['reverse-nodes-in-k-group', { values: [1, 2, 3, 4, 5], k: 3 }, [3, 2, 1, 4, 5]],
  ['reverse-nodes-in-k-group', { values: [], k: 2 }, []],
  ['reverse-nodes-in-k-group', { values: [1], k: 1 }, [1]],
  ['reverse-nodes-in-k-group', { values: [1, 2], k: 3 }, [1, 2]],
  ['reverse-nodes-in-k-group', { values: [1, 2, 3], k: 1 }, [1, 2, 3]],
  ['reverse-nodes-in-k-group', { values: [1, 2, 3, 4, 5, 6], k: 2 }, [2, 1, 4, 3, 6, 5]],
  ['reverse-nodes-in-k-group', { values: [7, 7, 7, 7], k: 3 }, [7, 7, 7, 7]],
  ['reverse-nodes-in-k-group', { values: [1, 2, 3, 4, 5, 6], k: 6 }, [6, 5, 4, 3, 2, 1]],
  ['copy-list-with-random-pointer', { nodes: [[7, null], [13, 0], [11, 4], [10, 2], [1, 0]] }, [[7, null], [13, 0], [11, 4], [10, 2], [1, 0]]],
  ['copy-list-with-random-pointer', { nodes: [] }, []],
  ['copy-list-with-random-pointer', { nodes: [[0, null]] }, [[0, null]]],
  ['copy-list-with-random-pointer', { nodes: [[0, 0]] }, [[0, 0]]],
  ['copy-list-with-random-pointer', { nodes: [[1, 1], [1, 0]] }, [[1, 1], [1, 0]]],
  ['copy-list-with-random-pointer', { nodes: [[1, 2], [2, 2], [3, 2]] }, [[1, 2], [2, 2], [3, 2]]],
  ['copy-list-with-random-pointer', { nodes: [[-10000, null], [10000, null]] }, [[-10000, null], [10000, null]]],
];
