import type { ProblemId } from '../src/engine/types';
export const orderingStructuresCases: [ProblemId, unknown, unknown][] = [
  ['first-missing-positive', { nums: [3,4,-1,1] }, 2],
  ['first-missing-positive', { nums: [] }, 1],
  ['first-missing-positive', { nums: [1,2,0] }, 3],
  ['first-missing-positive', { nums: [7,8,9,11,12] }, 1],
  ['first-missing-positive', { nums: [1,1] }, 2],
  ['first-missing-positive', { nums: [-10000,10000,2] }, 1],
  ['rotate-image', { matrix: [[1,2,3],[4,5,6],[7,8,9]] }, [[7,4,1],[8,5,2],[9,6,3]]],
  ['rotate-image', { matrix: [] }, []],
  ['rotate-image', { matrix: [[1]] }, [[1]]],
  ['rotate-image', { matrix: [[1,2],[3,4]] }, [[3,1],[4,2]]],
  ['rotate-image', { matrix: [[0,0],[0,0]] }, [[0,0],[0,0]]],
  ['rotate-image', { matrix: [[-10000,0],[0,10000]] }, [[0,-10000],[10000,0]]],
  ['search-a-2d-matrix', { matrix: [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target: 16 }, true],
  ['search-a-2d-matrix', { matrix: [], target: 0 }, false],
  ['search-a-2d-matrix', { matrix: [[1]], target: 1 }, true],
  ['search-a-2d-matrix', { matrix: [[1]], target: 0 }, false],
  ['search-a-2d-matrix', { matrix: [[1,3],[5,7]], target: 4 }, false],
  ['search-a-2d-matrix', { matrix: [[-10000],[0],[10000]], target: 10000 }, true],
  ['search-a-2d-matrix-ii', { matrix: [[1,4,7,11],[2,5,8,12],[3,6,9,16]], target: 6 }, true],
  ['search-a-2d-matrix-ii', { matrix: [], target: 0 }, false],
  ['search-a-2d-matrix-ii', { matrix: [[1,1],[1,1]], target: 1 }, true],
  ['search-a-2d-matrix-ii', { matrix: [[1,4],[2,5]], target: 3 }, false],
  ['search-a-2d-matrix-ii', { matrix: [[1]], target: 2 }, false],
  ['search-a-2d-matrix-ii', { matrix: [[-10000],[0],[10000]], target: -10000 }, true],
  ['find-minimum-in-rotated-sorted-array', { nums: [4,5,6,7,0,1,2] }, 0],
  ['find-minimum-in-rotated-sorted-array', { nums: [1] }, 1],
  ['find-minimum-in-rotated-sorted-array', { nums: [2,1] }, 1],
  ['find-minimum-in-rotated-sorted-array', { nums: [1,2] }, 1],
  ['find-minimum-in-rotated-sorted-array', { nums: [3,1,2] }, 1],
  ['find-minimum-in-rotated-sorted-array', { nums: [10000,-10000,0] }, -10000],
  ['median-of-two-sorted-arrays', { a: [1,3], b: [2,4,5,6] }, 3.5],
  ['median-of-two-sorted-arrays', { a: [], b: [1] }, 1],
  ['median-of-two-sorted-arrays', { a: [1,2,3], b: [] }, 2],
  ['median-of-two-sorted-arrays', { a: [0,0], b: [0,0] }, 0],
  ['median-of-two-sorted-arrays', { a: [-10000], b: [10000] }, 0],
  ['median-of-two-sorted-arrays', { a: [1,2], b: [3,4] }, 2.5],
  ['implement-trie-prefix-tree', { operations: [{ op:'insert',word:'apple' },{ op:'search',word:'app' },{ op:'startsWith',word:'app' },{ op:'insert',word:'app' },{ op:'search',word:'app' }] }, [null,false,true,null,true]],
  ['implement-trie-prefix-tree', { operations: [] }, []],
  ['implement-trie-prefix-tree', { operations: [{ op:'search',word:'' },{ op:'startsWith',word:'' },{ op:'insert',word:'' },{ op:'search',word:'' }] }, [false,true,null,true]],
  ['implement-trie-prefix-tree', { operations: [{ op:'insert',word:'a' },{ op:'insert',word:'a' },{ op:'search',word:'a' },{ op:'search',word:'ab' }] }, [null,null,true,false]],
  ['implement-trie-prefix-tree', { operations: [{ op:'insert',word:'ab' },{ op:'insert',word:'ac' },{ op:'search',word:'a' },{ op:'startsWith',word:'a' }] }, [null,null,false,true]],
  ['implement-trie-prefix-tree', { operations: [{ op:'search',word:'z' },{ op:'startsWith',word:'z' }] }, [false,false]],
  ['kth-largest-element-in-an-array', { nums: [3,2,1,5,6,4], k: 2 }, 5],
  ['kth-largest-element-in-an-array', { nums: [1], k: 1 }, 1],
  ['kth-largest-element-in-an-array', { nums: [2,2,1], k: 2 }, 2],
  ['kth-largest-element-in-an-array', { nums: [1,2,3], k: 3 }, 1],
  ['kth-largest-element-in-an-array', { nums: [-10000,10000], k: 1 }, 10000],
  ['kth-largest-element-in-an-array', { nums: [-2,-3,-1], k: 2 }, -2],
  ['top-k-frequent-elements', { nums: [1,1,1,2,2,3], k: 2 }, [1,2]],
  ['top-k-frequent-elements', { nums: [3,2,1], k: 2 }, [1,2]],
  ['top-k-frequent-elements', { nums: [1], k: 1 }, [1]],
  ['top-k-frequent-elements', { nums: [-1,-1,2,2,0], k: 2 }, [-1,2]],
  ['top-k-frequent-elements', { nums: [2,3,3,1,1], k: 3 }, [1,3,2]],
  ['top-k-frequent-elements', { nums: [-10000,10000,-10000], k: 1 }, [-10000]],
  ['find-median-from-data-stream', { operations: [{op:'addNum',value:1},{op:'addNum',value:2},{op:'findMedian'},{op:'addNum',value:3},{op:'findMedian'}] }, [null,null,1.5,null,2]],
  ['find-median-from-data-stream', { operations: [] }, []],
  ['find-median-from-data-stream', { operations: [{op:'addNum',value:-1},{op:'findMedian'},{op:'findMedian'}] }, [null,-1,-1]],
  ['find-median-from-data-stream', { operations: [{op:'addNum',value:0},{op:'addNum',value:0},{op:'findMedian'}] }, [null,null,0]],
  ['find-median-from-data-stream', { operations: [{op:'addNum',value:10000},{op:'addNum',value:-10000},{op:'findMedian'}] }, [null,null,0]],
  ['find-median-from-data-stream', { operations: [{op:'addNum',value:5},{op:'addNum',value:4},{op:'addNum',value:3},{op:'findMedian'}] }, [null,null,null,4]],
];
