import type { ProblemId } from '../src/engine/types';
import { stackWindowCases } from './stack-window-cases';
import { linkedListCases } from './linked-list-cases';
import { treeCases } from './tree-cases';
import { advancedCases } from './advanced-cases';
import { explorationCases } from './exploration-cases';
import { orderingStructuresCases } from './ordering-structures-cases';
import { dpGreedyCases } from './dp-greedy-cases';
import { finalSixCases } from './final-six-cases';

export const cases: [ProblemId, unknown, unknown][] = [
  ...finalSixCases,
  ...dpGreedyCases,
  ...treeCases,
  ...advancedCases,
  ...explorationCases,
  ...orderingStructuresCases,
  ...linkedListCases,
  ...stackWindowCases,
  ['3sum', { nums: [-1, 0, 1, 2, -1, -4] }, [[-1, -1, 2], [-1, 0, 1]]],
  ['3sum', { nums: [0, 0, 0, 0] }, [[0, 0, 0]]],
  ['3sum', { nums: [-2, 0, 0, 2, 2] }, [[-2, 0, 2]]],
  ['3sum', { nums: [-10000, 0, 10000] }, [[-10000, 0, 10000]]],
  ['3sum', { nums: [-1, 1] }, []],
  ['3sum', { nums: [] }, []],
  ['sort-colors', { nums: [2, 0, 2, 1, 1, 0] }, [0, 0, 1, 1, 2, 2]],
  ['sort-colors', { nums: [1, 2, 0] }, [0, 1, 2]],
  ['sort-colors', { nums: [2, 2] }, [2, 2]],
  ['sort-colors', { nums: [0] }, [0]],
  ['sort-colors', { nums: [] }, []],
  ['rotate-array', { nums: [1, 2, 3, 4, 5, 6, 7], k: 3 }, [5, 6, 7, 1, 2, 3, 4]],
  ['rotate-array', { nums: [1, 2, 3], k: 4 }, [3, 1, 2]],
  ['rotate-array', { nums: [1, 1, 2, 2], k: 2 }, [2, 2, 1, 1]],
  ['rotate-array', { nums: [1, 2], k: 0 }, [1, 2]],
  ['rotate-array', { nums: [1], k: 1000000000 }, [1]],
  ['rotate-array', { nums: [], k: 10 }, []],
  ['next-permutation', { nums: [1, 3, 5, 4, 2] }, [1, 4, 2, 3, 5]],
  ['next-permutation', { nums: [3, 2, 1] }, [1, 2, 3]],
  ['next-permutation', { nums: [1, 1, 5] }, [1, 5, 1]],
  ['next-permutation', { nums: [2, 2] }, [2, 2]],
  ['next-permutation', { nums: [-1, 1, 0] }, [0, -1, 1]],
  ['next-permutation', { nums: [3] }, [3]],
  ['next-permutation', { nums: [] }, []],
  ['merge-intervals', { intervals: [[8, 10], [1, 3], [2, 6], [15, 18]] }, [[1, 6], [8, 10], [15, 18]]],
  ['merge-intervals', { intervals: [[1, 4], [4, 5]] }, [[1, 5]]],
  ['merge-intervals', { intervals: [[1, 10], [2, 3], [1, 10]] }, [[1, 10]]],
  ['merge-intervals', { intervals: [[0, 0], [1, 1]] }, [[0, 0], [1, 1]]],
  ['merge-intervals', { intervals: [[-2, 1], [-3, -2], [5, 5]] }, [[-3, 1], [5, 5]]],
  ['merge-intervals', { intervals: [] }, []],
  ['group-anagrams', { strs: ['eat', 'tea', 'tan', 'ate', 'nat', 'bat'] }, [['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']]],
  ['group-anagrams', { strs: ['', 'a', '', 'a'] }, [['', ''], ['a', 'a']]],
  ['group-anagrams', { strs: [] }, []],
  ['group-anagrams', { strs: ['ab', 'aab', 'ba', 'baa'] }, [['ab', 'ba'], ['aab', 'baa']]],
  ['longest-consecutive-sequence', { nums: [100, 4, 200, 1, 3, 2] }, 4],
  ['longest-consecutive-sequence', { nums: [0, -1, -1, 2, 1] }, 4],
  ['longest-consecutive-sequence', { nums: [2, 2, 2] }, 1],
  ['longest-consecutive-sequence', { nums: [] }, 0],
  ['longest-consecutive-sequence', { nums: [-10000, 10000] }, 1],
  ['product-of-array-except-self', { nums: [1, 2, 3, 4] }, [24, 12, 8, 6]],
  ['product-of-array-except-self', { nums: [-1, 1, 0, -3, 3] }, [0, 0, 9, 0, 0]],
  ['product-of-array-except-self', { nums: [0, 0, 3] }, [0, 0, 0]],
  ['product-of-array-except-self', { nums: [-2, 3, -4] }, [-12, 8, -6]],
  ['product-of-array-except-self', { nums: [] }, []],
  ['product-of-array-except-self', { nums: [0] }, [1]],
  ['product-of-array-except-self', { nums: Array(12).fill(5) }, Array(12).fill(48828125)],
  ['subarray-sum-equals-k', { nums: [1, -1, 1, 1, -1], k: 1 }, 7],
  ['subarray-sum-equals-k', { nums: [1, 1, 1], k: 2 }, 2],
  ['subarray-sum-equals-k', { nums: [0, 0, 0], k: 0 }, 6],
  ['subarray-sum-equals-k', { nums: [-1, -1, 1], k: 0 }, 1],
  ['subarray-sum-equals-k', { nums: [1], k: 1 }, 1],
  ['subarray-sum-equals-k', { nums: [1], k: 0 }, 0],
  ['subarray-sum-equals-k', { nums: [], k: 0 }, 0],
  ['search-insert-position', { nums: [1, 3, 5, 6], target: 2 }, 1],
  ['search-insert-position', { nums: [1, 3, 5, 6], target: 5 }, 2],
  ['search-insert-position', { nums: [1, 3, 5, 6], target: 7 }, 4],
  ['search-insert-position', { nums: [-4, -1, 3], target: -5 }, 0],
  ['search-insert-position', { nums: [], target: 0 }, 0],
  ['search-insert-position', { nums: [1], target: 1 }, 0],
  ['find-first-and-last-position-of-element-in-sorted-array', { nums: [5, 7, 7, 8, 8, 10], target: 8 }, [3, 4]],
  ['find-first-and-last-position-of-element-in-sorted-array', { nums: [5, 7, 7, 8, 8, 10], target: 6 }, [-1, -1]],
  ['find-first-and-last-position-of-element-in-sorted-array', { nums: [2, 2, 2], target: 2 }, [0, 2]],
  ['find-first-and-last-position-of-element-in-sorted-array', { nums: [], target: 0 }, [-1, -1]],
  ['find-first-and-last-position-of-element-in-sorted-array', { nums: [0], target: 0 }, [0, 0]],
  ['find-first-and-last-position-of-element-in-sorted-array', { nums: [-2, -2, 0], target: -2 }, [0, 1]],
  ['find-first-and-last-position-of-element-in-sorted-array', { nums: [1, 2], target: 3 }, [-1, -1]],
  ['search-in-rotated-sorted-array', { nums: [4, 5, 6, 7, 0, 1, 2], target: 0 }, 4],
  ['search-in-rotated-sorted-array', { nums: [4, 5, 6, 7, 0, 1, 2], target: 3 }, -1],
  ['search-in-rotated-sorted-array', { nums: [1, 2, 3, 4], target: 4 }, 3],
  ['search-in-rotated-sorted-array', { nums: [3, 1], target: 1 }, 1],
  ['search-in-rotated-sorted-array', { nums: [1], target: 0 }, -1],
  ['search-in-rotated-sorted-array', { nums: [1], target: 1 }, 0],
  ['search-in-rotated-sorted-array', { nums: [], target: 0 }, -1],
  ['best-time-to-buy-and-sell-stock', { prices: [7, 1, 5, 3, 6, 4] }, 5],
  ['best-time-to-buy-and-sell-stock', { prices: [7, 6, 4, 3, 1] }, 0],
  ['best-time-to-buy-and-sell-stock', { prices: [2, 2, 2] }, 0],
  ['best-time-to-buy-and-sell-stock', { prices: [9, 1, 2, 0] }, 1],
  ['best-time-to-buy-and-sell-stock', { prices: [] }, 0],
  ['best-time-to-buy-and-sell-stock', { prices: [0] }, 0],
  ['jump-game', { nums: [2, 3, 1, 1, 4] }, true],
  ['jump-game', { nums: [3, 2, 1, 0, 4] }, false],
  ['jump-game', { nums: [0] }, true],
  ['jump-game', { nums: [0, 10000] }, false],
  ['jump-game', { nums: [10000, 0] }, true],
  ['jump-game', { nums: [1, 1, 0] }, true],
  ['two-sum', { nums: [2, 7, 11, 15], target: 9 }, [0, 1]],
  ['two-sum', { nums: [3, 3], target: 6 }, [0, 1]],
  ['two-sum', { nums: [0, -2, 5, 2], target: 0 }, [1, 3]],
  ['two-sum', { nums: [3], target: 6 }, []],
  ['two-sum', { nums: [], target: 0 }, []],
  ['move-zeroes', { nums: [0, 1, 0, 3, 12] }, [1, 3, 12, 0, 0]],
  ['move-zeroes', { nums: [0, 0] }, [0, 0]],
  ['move-zeroes', { nums: [] }, []],
  ['container-with-most-water', { heights: [1, 8, 6, 2, 5, 4, 8, 3, 7] }, 49],
  ['container-with-most-water', { heights: [0, 0] }, 0],
  ['container-with-most-water', { heights: [1, 1] }, 1],
  ['longest-substring-without-repeating-characters', { s: 'abcabcbb' }, 3],
  ['longest-substring-without-repeating-characters', { s: 'abba' }, 2],
  ['longest-substring-without-repeating-characters', { s: '' }, 0],
  ['longest-substring-without-repeating-characters', { s: '你好你🙂好' }, 3],
  ['maximum-subarray', { nums: [-2, 1, -3, 4, -1, 2, 1, -5, 4] }, 6],
  ['maximum-subarray', { nums: [-3, -1, -2] }, -1],
  ['maximum-subarray', { nums: [0] }, 0],
  ['reverse-linked-list', { values: [1, 2, 3, 4, 5] }, [5, 4, 3, 2, 1]],
  ['reverse-linked-list', { values: [2, 2] }, [2, 2]],
  ['reverse-linked-list', { values: [] }, []],
  ['binary-tree-level-order-traversal', { tree: [3, 9, 20, null, null, 15, 7] }, [[3], [9, 20], [15, 7]]],
  ['binary-tree-level-order-traversal', { tree: [1, null, 2, 3] }, [[1], [2], [3]]],
  ['binary-tree-level-order-traversal', { tree: [1, 1, 1] }, [[1], [1, 1]]],
  ['binary-tree-level-order-traversal', { tree: [] }, []],
  ['binary-tree-level-order-traversal', { tree: [null] }, []],
  ['climbing-stairs', { n: 0 }, 1],
  ['climbing-stairs', { n: 1 }, 1],
  ['climbing-stairs', { n: 7 }, 21],
  ['coin-change', { coins: [1, 2, 5], amount: 11 }, 3],
  ['coin-change', { coins: [2], amount: 3 }, -1],
  ['coin-change', { coins: [2], amount: 0 }, 0],
  ['longest-increasing-subsequence', { nums: [10, 9, 2, 5, 3, 7, 101, 18] }, 4],
  ['longest-increasing-subsequence', { nums: [2, 2, 2] }, 1],
  ['longest-increasing-subsequence', { nums: [] }, 0],
];
