import type { ProblemId } from '../src/engine/types';

export const stackWindowCases: [ProblemId, unknown, unknown][] = [
  ['valid-parentheses', { s: '{[()]}' }, true],
  ['valid-parentheses', { s: '' }, true],
  ['valid-parentheses', { s: ']' }, false],
  ['valid-parentheses', { s: '([)]' }, false],
  ['valid-parentheses', { s: '(((' }, false],
  ['valid-parentheses', { s: ')(' }, false],
  ['valid-parentheses', { s: '()[]{}' }, true],
  ['min-stack', { operations: [] }, []],
  ['min-stack', { operations: [{ op: 'push', value: -2 }, { op: 'push', value: 0 }, { op: 'push', value: -3 }, { op: 'getMin' }, { op: 'pop' }, { op: 'top' }, { op: 'getMin' }] }, [null, null, null, -3, null, 0, -2]],
  ['min-stack', { operations: [{ op: 'push', value: 1 }, { op: 'push', value: 1 }, { op: 'pop' }, { op: 'getMin' }] }, [null, null, null, 1]],
  ['min-stack', { operations: [{ op: 'push', value: 2 }, { op: 'pop' }, { op: 'push', value: 3 }, { op: 'top' }] }, [null, null, null, 3]],
  ['min-stack', { operations: [{ op: 'push', value: -10000 }, { op: 'push', value: 10000 }, { op: 'top' }, { op: 'getMin' }] }, [null, null, 10000, -10000]],
  ['daily-temperatures', { temperatures: [73, 74, 75, 71, 69, 72, 76, 73] }, [1, 1, 4, 2, 1, 1, 0, 0]],
  ['daily-temperatures', { temperatures: [] }, []],
  ['daily-temperatures', { temperatures: [20] }, [0]],
  ['daily-temperatures', { temperatures: [20, 20, 20] }, [0, 0, 0]],
  ['daily-temperatures', { temperatures: [30, 20, 10] }, [0, 0, 0]],
  ['daily-temperatures', { temperatures: [30, 40, 30, 50] }, [1, 2, 1, 0]],
  ['daily-temperatures', { temperatures: [-100, 100] }, [1, 0]],
  ['largest-rectangle-in-histogram', { heights: [2, 1, 5, 6, 2, 3] }, 10],
  ['largest-rectangle-in-histogram', { heights: [] }, 0],
  ['largest-rectangle-in-histogram', { heights: [0, 0] }, 0],
  ['largest-rectangle-in-histogram', { heights: [2, 2, 2] }, 6],
  ['largest-rectangle-in-histogram', { heights: [1, 2, 3, 4] }, 6],
  ['largest-rectangle-in-histogram', { heights: [4, 3, 2, 1] }, 6],
  ['largest-rectangle-in-histogram', { heights: [2, 0, 2] }, 2],
  ['trapping-rain-water', { heights: [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1] }, 6],
  ['trapping-rain-water', { heights: [] }, 0],
  ['trapping-rain-water', { heights: [3] }, 0],
  ['trapping-rain-water', { heights: [3, 0, 3] }, 3],
  ['trapping-rain-water', { heights: [5, 2, 1, 2, 1, 5] }, 14],
  ['trapping-rain-water', { heights: [2, 0, 2, 0, 2] }, 4],
  ['trapping-rain-water', { heights: [0, 1, 2] }, 0],
  ['sliding-window-maximum', { nums: [1, 3, -1, -3, 5, 3, 6, 7], k: 3 }, [3, 3, 5, 5, 6, 7]],
  ['sliding-window-maximum', { nums: [2, 2, 2], k: 2 }, [2, 2]],
  ['sliding-window-maximum', { nums: [-3, -2, -5], k: 2 }, [-2, -2]],
  ['sliding-window-maximum', { nums: [1, 3, 2], k: 1 }, [1, 3, 2]],
  ['sliding-window-maximum', { nums: [1, 3, 2], k: 3 }, [3]],
  ['sliding-window-maximum', { nums: [-10000, 10000], k: 2 }, [10000]],
  ['find-all-anagrams-in-a-string', { s: 'cbaebabacd', p: 'abc' }, [0, 6]],
  ['find-all-anagrams-in-a-string', { s: 'aaaa', p: 'aa' }, [0, 1, 2]],
  ['find-all-anagrams-in-a-string', { s: '', p: 'a' }, []],
  ['find-all-anagrams-in-a-string', { s: 'a', p: 'aa' }, []],
  ['find-all-anagrams-in-a-string', { s: 'baaab', p: 'aab' }, [0, 2]],
  ['find-all-anagrams-in-a-string', { s: 'aAbA', p: 'Ab' }, [1, 2]],
  ['find-all-anagrams-in-a-string', { s: 'abc', p: 'z' }, []],
  ['minimum-window-substring', { s: 'ADOBECODEBANC', t: 'ABC' }, 'BANC'],
  ['minimum-window-substring', { s: '', t: 'a' }, ''],
  ['minimum-window-substring', { s: 'abc', t: '' }, ''],
  ['minimum-window-substring', { s: 'a', t: 'aa' }, ''],
  ['minimum-window-substring', { s: 'AAABBC', t: 'AABC' }, 'AABBC'],
  ['minimum-window-substring', { s: 'abxba', t: 'ab' }, 'ab'],
  ['minimum-window-substring', { s: 'aA', t: 'AA' }, ''],
  ['longest-valid-parentheses', { s: ')()())' }, 4],
  ['longest-valid-parentheses', { s: '' }, 0],
  ['longest-valid-parentheses', { s: '(((' }, 0],
  ['longest-valid-parentheses', { s: ')))' }, 0],
  ['longest-valid-parentheses', { s: '(()' }, 2],
  ['longest-valid-parentheses', { s: '()(())' }, 6],
  ['longest-valid-parentheses', { s: ')()(()' }, 2],
  ['decode-string', { s: '3[a2[c]]' }, 'accaccacc'],
  ['decode-string', { s: '' }, ''],
  ['decode-string', { s: 'abc' }, 'abc'],
  ['decode-string', { s: '2[ab]3[c]' }, 'ababccc'],
  ['decode-string', { s: '10[a]' }, 'aaaaaaaaaa'],
  ['decode-string', { s: 'a2[b3[c]]d' }, 'abcccbcccd'],
  ['decode-string', { s: '1[1[1[1[1[1[a]]]]]]' }, 'a'],
];
