import type { ProblemId } from '../src/engine/types';

export const treeCases: [ProblemId, unknown, unknown][] = [
  ['binary-tree-inorder-traversal', { tree: [1, null, 2, 3] }, [1, 3, 2]],
  ['binary-tree-inorder-traversal', { tree: [] }, []],
  ['binary-tree-inorder-traversal', { tree: [0] }, [0]],
  ['binary-tree-inorder-traversal', { tree: [2, 1, 3] }, [1, 2, 3]],
  ['binary-tree-inorder-traversal', { tree: [1, 1, 1] }, [1, 1, 1]],
  ['binary-tree-inorder-traversal', { tree: [1, 2, null, 3] }, [3, 2, 1]],
  ['maximum-depth-of-binary-tree', { tree: [3, 9, 20, null, null, 15, 7] }, 3],
  ['maximum-depth-of-binary-tree', { tree: [] }, 0],
  ['maximum-depth-of-binary-tree', { tree: [null, null] }, 0],
  ['maximum-depth-of-binary-tree', { tree: [0] }, 1],
  ['maximum-depth-of-binary-tree', { tree: [1, null, 2, null, 3, null, 4, null, 5] }, 5],
  ['maximum-depth-of-binary-tree', { tree: [1, 2, 3] }, 2],
  ['invert-binary-tree', { tree: [4, 2, 7, 1, 3, 6, 9] }, [4, 7, 2, 9, 6, 3, 1]],
  ['invert-binary-tree', { tree: [] }, []],
  ['invert-binary-tree', { tree: [0] }, [0]],
  ['invert-binary-tree', { tree: [1, null, 2, 3] }, [1, 2, null, null, 3]],
  ['invert-binary-tree', { tree: [1, 2] }, [1, null, 2]],
  ['invert-binary-tree', { tree: [1, 1, 1] }, [1, 1, 1]],
  ['symmetric-tree', { tree: [1, 2, 2, 3, 4, 4, 3] }, true],
  ['symmetric-tree', { tree: [] }, true],
  ['symmetric-tree', { tree: [0] }, true],
  ['symmetric-tree', { tree: [1, 2, 2, null, 3, null, 3] }, false],
  ['symmetric-tree', { tree: [1, 2, 2, null, 3, 3, null] }, true],
  ['symmetric-tree', { tree: [1, 2, 3] }, false],
  ['diameter-of-binary-tree', { tree: [1, 2, 3, 4, 5] }, 3],
  ['diameter-of-binary-tree', { tree: [] }, 0],
  ['diameter-of-binary-tree', { tree: [0] }, 0],
  ['diameter-of-binary-tree', { tree: [1, null, 2, null, 3, null, 4, null, 5] }, 4],
  ['diameter-of-binary-tree', { tree: [0, 1, null, 2, 3, 4, null, null, 5, 6, null, null, 7] }, 6],
  ['diameter-of-binary-tree', { tree: [1, 1, 1] }, 2],
  ['convert-sorted-array-to-binary-search-tree', { nums: [-10, -3, 0, 5, 9] }, [0, -10, 5, null, -3, null, 9]],
  ['convert-sorted-array-to-binary-search-tree', { nums: [] }, []],
  ['convert-sorted-array-to-binary-search-tree', { nums: [0] }, [0]],
  ['convert-sorted-array-to-binary-search-tree', { nums: [1, 2] }, [1, null, 2]],
  ['convert-sorted-array-to-binary-search-tree', { nums: [1, 2, 3, 4] }, [2, 1, 3, null, null, null, 4]],
  ['convert-sorted-array-to-binary-search-tree', { nums: [-10000, 10000] }, [-10000, null, 10000]],
  ['validate-binary-search-tree', { tree: [5, 1, 7, null, null, 4, 8] }, false],
  ['validate-binary-search-tree', { tree: [] }, true],
  ['validate-binary-search-tree', { tree: [0] }, true],
  ['validate-binary-search-tree', { tree: [2, 1, 3] }, true],
  ['validate-binary-search-tree', { tree: [2, 1, 2] }, false],
  ['validate-binary-search-tree', { tree: [0, -10000, 10000] }, true],
  ['kth-smallest-element-in-a-bst', { tree: [3, 1, 4, null, 2], k: 1 }, 1],
  ['kth-smallest-element-in-a-bst', { tree: [3, 1, 4, null, 2], k: 3 }, 3],
  ['kth-smallest-element-in-a-bst', { tree: [3, 1, 4, null, 2], k: 4 }, 4],
  ['kth-smallest-element-in-a-bst', { tree: [5, 3, 7, 2, 4, 6, 8], k: 7 }, 8],
  ['kth-smallest-element-in-a-bst', { tree: [0], k: 1 }, 0],
  ['kth-smallest-element-in-a-bst', { tree: [-2, -3, -1], k: 2 }, -2],
  ['binary-tree-right-side-view', { tree: [1, 2, 3, null, 5, null, 4] }, [1, 3, 4]],
  ['binary-tree-right-side-view', { tree: [] }, []],
  ['binary-tree-right-side-view', { tree: [0] }, [0]],
  ['binary-tree-right-side-view', { tree: [1, 2, 3, 4, null, null, null, 5] }, [1, 3, 4, 5]],
  ['binary-tree-right-side-view', { tree: [1, 2, null, 3] }, [1, 2, 3]],
  ['binary-tree-right-side-view', { tree: [1, 2, 2] }, [1, 2]],
  ['flatten-binary-tree-to-linked-list', { tree: [1, 2, 5, 3, 4, null, 6] }, [1, 2, 3, 4, 5, 6]],
  ['flatten-binary-tree-to-linked-list', { tree: [] }, []],
  ['flatten-binary-tree-to-linked-list', { tree: [0] }, [0]],
  ['flatten-binary-tree-to-linked-list', { tree: [1, null, 2, 3] }, [1, 2, 3]],
  ['flatten-binary-tree-to-linked-list', { tree: [1, 1, 1, 1, 1] }, [1, 1, 1, 1, 1]],
  ['flatten-binary-tree-to-linked-list', { tree: [1, 2, null, 3] }, [1, 2, 3]],
];
