import type { Problem } from '../types';
import { linkedListReferences as references } from './linked-list-references';

export const linkedListProblems: Problem[] = [
  {
    id: 'intersection-of-two-linked-lists', number: 160, title: '相交链表', english: 'Intersection of Two Linked Lists', category: '链表', difficulty: '简单', renderer: 'linked-lab',
    summary: '寻找两个无环链表共享的第一个节点。返回它在 A、B 中的下标与节点值；没有共享节点返回 null。值相等并不代表相交。',
    idea: '两个指针走完各自链表后，转到另一条链的头。分别走 A+B 与 B+A，独有前缀长度差被抵消，最终在共享节点或 null 相遇。',
    invariant: '比较的是节点身份。shared 只创建一次，两条前缀都连接到同一个共享头，不复制成两份。',
    time: 'O(m + n)', space: 'O(1)', sample: { prefixA: [4, 1], prefixB: [5, 6, 1], shared: [8, 4, 5] },
    inputHint: 'prefixA、prefixB、shared：各最多 12 个整数，总节点数 ≤18，值 −10000–10000；shared=[] 表示不相交。返回 {indexA,indexB,value} 或 null，下标从 0 开始。', code: references['intersection-of-two-linked-lists'],
  },
  {
    id: 'palindrome-linked-list', number: 234, title: '回文链表', english: 'Palindrome Linked List', category: '链表', difficulty: '简单', renderer: 'linked-lab',
    summary: '判断链表从前往后和从后往前读是否相同。使用常数辅助指针，返回前恢复原链表；空链表也是回文。',
    idea: '快慢指针定位前半段尾部，反转后半段进行一一比较，再反转一次恢复连接，不需要把值复制到数组判断。',
    invariant: '比较时后半段按相反方向读取；无论判断结果如何，结束时所有原节点的 next 恢复不变。',
    time: 'O(n)', space: 'O(1)', sample: { values: [1, 2, 2, 1] },
    inputHint: 'values：0–12 个整数，范围 −10000–10000；空链表返回 true。', code: references['palindrome-linked-list'],
  },
  {
    id: 'linked-list-cycle', number: 141, title: '环形链表', english: 'Linked List Cycle', category: '链表', difficulty: '简单', renderer: 'linked-lab',
    summary: '判断从头节点出发是否会沿 next 再次访问同一个节点。pos 只定义输入如何连接，不作为算法的答案提示。',
    idea: '慢指针走一步，快指针走两步。有环时快指针最终追上慢指针，无环时快指针会先到达 null。',
    invariant: '初始重合不算发现环，必须在移动后比较身份；节点值重复也不影响判断。',
    time: 'O(n)', space: 'O(1)', sample: { values: [3, 2, 0, -4], pos: 1 },
    inputHint: 'values：0–12 个整数；pos=-1 表示无环，否则尾节点连向该下标，须在 values 范围内。空输入仅允许 pos=-1。', code: references['linked-list-cycle'],
  },
  {
    id: 'linked-list-cycle-ii', number: 142, title: '环形链表 II', english: 'Linked List Cycle II', category: '链表', difficulty: '中等', renderer: 'linked-lab',
    summary: '找出链表环入口，返回其在输入 values 中的下标；无环返回 null，不改变连接。',
    idea: '快慢指针先在环内相遇，再把其中一个放回头节点。两者此后同速前进，下一次相遇就在入口。',
    invariant: '第一阶段确认有环；第二阶段一个从头出发，一个从相遇处出发，均一次走一步。',
    time: 'O(n)', space: 'O(1)', sample: { values: [3, 2, 0, -4], pos: 1 },
    inputHint: 'values：0–12 个整数；pos=-1 或合法下标。结果是入口下标，不是节点值；算法只读取构造后的链表。', code: references['linked-list-cycle-ii'],
  },
  {
    id: 'merge-two-sorted-lists', number: 21, title: '合并两个有序链表', english: 'Merge Two Sorted Lists', category: '链表', difficulty: '简单', renderer: 'linked-lab',
    summary: '把两个独立的非递减链表合并成一条非递减链表。复用原节点，返回按连接顺序排列的值数组。',
    idea: '用哨兵和结果尾指针，每次选较小的当前头节点。一个链表用完后，将另一条剩余尾部整体接上。',
    invariant: '已选出的结果前缀非递减；值相同时先选择 A，且每个输入节点在结果中恰好出现一次。',
    time: 'O(m + n)', space: 'O(1)', sample: { a: [1, 2, 4], b: [1, 3, 4] },
    inputHint: 'a、b：各 0–12 个非递减整数，总数 ≤18；范围 −10000–10000。不会默默排序非法输入。', code: references['merge-two-sorted-lists'],
  },
  {
    id: 'add-two-numbers', number: 2, title: '两数相加', english: 'Add Two Numbers', category: '链表', difficulty: '中等', renderer: 'linked-lab',
    summary: '两个非负整数以逆序数字链表表示，即个位在前。逐位相加并返回同样逆序的结果数字，保留最终进位。',
    idea: '每轮将两个当前数字与上轮进位相加，个位生成新节点，十位作为下一轮进位；较短链表结束后按 0 处理。',
    invariant: '已经生成的低位数字不会再改变，进位始终为 0 或 1；输入节点和连接保持不变。',
    time: 'O(max(m, n))', space: 'O(1) 不含结果', sample: { a: [2, 4, 3], b: [5, 6, 4] },
    inputHint: 'a、b：各 1–8 个 0–9 的整数，低位在左。多位数最后一项不能为 0；数字 0 表示为 [0]。返回逆序数字数组。', code: references['add-two-numbers'],
  },
  {
    id: 'remove-nth-node-from-end-of-list', number: 19, title: '删除链表的倒数第 N 个结点', english: 'Remove Nth Node From End of List', category: '链表', difficulty: '中等', renderer: 'linked-lab',
    summary: '删除倒数第 n 个节点，返回剩余链表的值序列。倒数从 1 开始，删除头节点和唯一节点也适用。',
    idea: '从哨兵出发让 fast 先走 n 步，然后两个指针同速前进；fast 到尾部时，slow 恰好位于待删节点之前。',
    invariant: '双指针推进时保持 n 条 next 边的间距，只改变前驱连接，不把后继的值拷到待删节点。',
    time: 'O(n)', space: 'O(1)', sample: { values: [1, 2, 3, 4, 5], n: 2 },
    inputHint: 'values：1–12 个整数，范围 −10000–10000；n：1 到链表长度的整数。被绕过节点不属于返回链表。', code: references['remove-nth-node-from-end-of-list'],
  },
  {
    id: 'swap-nodes-in-pairs', number: 24, title: '两两交换链表中的节点', english: 'Swap Nodes in Pairs', category: '链表', difficulty: '中等', renderer: 'linked-lab',
    summary: '每两个相邻节点交换位置，不能只交换值；最后不足两个的节点保持原样。',
    idea: 'before 指向一组之前，先让第一节点接向后续，再让第二节点指向第一，最后把 before 接到第二节点。',
    invariant: '每一步都保留未处理后缀，节点身份和值保持不变；只有 next 连接改变。',
    time: 'O(n)', space: 'O(1)', sample: { values: [1, 2, 3, 4, 5] },
    inputHint: 'values：0–12 个整数，范围 −10000–10000。空输入返回 []，奇数尾节点保留。', code: references['swap-nodes-in-pairs'],
  },
  {
    id: 'reverse-nodes-in-k-group', number: 25, title: 'K 个一组翻转链表', english: 'Reverse Nodes in k-Group', category: '链表', difficulty: '困难', renderer: 'linked-lab',
    summary: '每连续 k 个节点为一组反转连接，剩余不足 k 个的尾部不反转，返回结果值序列。',
    idea: '先向前探测是否有完整一组，再保存下一组入口、逐条反转组内 next，最后把前一组接到新组头。',
    invariant: '反转过程中保存旧后继与下一组入口；完成一组后原组头成为组尾，仍连着尚未处理部分。',
    time: 'O(n)', space: 'O(1)', sample: { values: [1, 2, 3, 4, 5], k: 3 },
    inputHint: 'values：0–12 个整数，范围 −10000–10000；k：1–12 的整数。允许 k 大于长度，此时整体不变。', code: references['reverse-nodes-in-k-group'],
  },
  {
    id: 'copy-list-with-random-pointer', number: 138, title: '随机链表的复制', english: 'Copy List with Random Pointer', category: '链表', difficulty: '中等', renderer: 'linked-lab',
    summary: '复制含 next 与 random 指针的链表。新链表的值和指向关系相同，但不能有任何指针指回原节点。',
    idea: '第一遍给每个原节点分配一个新节点，建立身份映射；第二遍通过映射设置新节点的 next 和 random。',
    invariant: '原链表不改变。每个原节点对应恰好一个新节点，新 next/random 只指向新节点或 null。',
    time: 'O(n)', space: 'O(n)', sample: { nodes: [[7, null], [13, 0], [11, 4], [10, 2], [1, 0]] },
    inputHint: 'nodes：最多 10 个 [value, randomIndex]；value 范围 −10000–10000；randomIndex 为 null 或合法下标。next 默认连接下一项，允许 random 自指或交叉。', code: references['copy-list-with-random-pointer'],
  },
];
