import type { Problem } from '../types';
import { stackWindowReferences as references } from './stack-window-references';

export const stackWindowProblems: Problem[] = [
  {
    id: 'valid-parentheses', number: 20, title: '有效的括号', english: 'Valid Parentheses', category: '栈', difficulty: '简单', renderer: 'stack-window',
    summary: '判断圆括号、方括号和花括号能否按正确类型与嵌套顺序全部匹配。空字符串有效。',
    idea: '最近出现的左括号必须最先闭合。左括号入栈，右括号检查并弹出栈顶；错配、缺少左括号或最终有剩余都失败。',
    invariant: '栈从底到顶保留尚未匹配的左括号，已配对部分不会再次入栈。',
    time: 'O(n)', space: 'O(n)', sample: { s: '{[()]}' },
    inputHint: 's：0–32 个字符，只能使用 ()[]{}；空字符串返回 true。', code: references['valid-parentheses'],
  },
  {
    id: 'min-stack', number: 155, title: '最小栈', english: 'Min Stack', category: '栈', difficulty: '中等', renderer: 'stack-window',
    summary: '维护支持 push、pop、top、getMin 的栈，每次操作都在常数时间内完成。返回每次操作的结果序列。',
    idea: '每层同时保存值与截至该层的最小值。弹出栈顶时，不必重新扫描，下一层已经记录了它的最小值。',
    invariant: '每一层的 minimum 等于从栈底到该层的最小值，重复最小值也拥有独立记录。',
    time: '每次 O(1)', space: 'O(n)', sample: { operations: [{ op: 'push', value: -2 }, { op: 'push', value: 0 }, { op: 'push', value: -3 }, { op: 'getMin' }, { op: 'pop' }, { op: 'top' }, { op: 'getMin' }] },
    inputHint: 'operations：最多 24 次操作；push 需要整数 value（−10000–10000），其余操作不带 value。初始为空栈，禁止空栈 pop/top/getMin；push/pop 返回 null。', code: references['min-stack'],
  },
  {
    id: 'daily-temperatures', number: 739, title: '每日温度', english: 'Daily Temperatures', category: '单调栈', difficulty: '中等', renderer: 'stack-window',
    summary: '对每一天，求要等几天才会出现严格更高的温度；之后没有更暖日期则返回 0。',
    idea: '把还在等待的日期放进单调栈。一旦今天比栈顶更暖，就结算那天的等待距离，直到栈顶不再更冷。',
    invariant: '栈内下标递增、温度非递增；弹出的日期第一次遇到更暖日，等待距离已确定。',
    time: 'O(n)', space: 'O(n)', sample: { temperatures: [73, 74, 75, 71, 69, 72, 76, 73] },
    inputHint: 'temperatures：0–24 个整数，范围 −100–100；同温度不算更暖。', code: references['daily-temperatures'],
  },
  {
    id: 'largest-rectangle-in-histogram', number: 84, title: '柱状图中最大的矩形', english: 'Largest Rectangle in Histogram', category: '单调栈', difficulty: '困难', renderer: 'stack-window',
    summary: '每根柱子宽度为 1，求能完全容纳在连续柱子下方的最大矩形面积。',
    idea: '栈保存非递减高度。遇到更矮柱子，弹出旧高度，利用当前右边界与弹出后的左邻计算可延伸宽度；末尾统一结算。',
    invariant: '栈内高度非递减。每根柱子只入栈、出栈一次；面积使用 i − left − 1，不把两侧边界柱计入。',
    time: 'O(n)', space: 'O(n)', sample: { heights: [2, 1, 5, 6, 2, 3] },
    inputHint: 'heights：0–24 个整数，范围 0–100；空数组或全零返回 0。', code: references['largest-rectangle-in-histogram'],
  },
  {
    id: 'trapping-rain-water', number: 42, title: '接雨水', english: 'Trapping Rain Water', category: '单调栈', difficulty: '困难', renderer: 'stack-window',
    summary: '柱宽均为 1，求雨后被两侧柱子围住的总水量；两端外侧不蓄水。',
    idea: '右侧出现更高柱子时，弹出凹槽底部。只有仍有左墙才可蓄水，新增高度取较矮墙减去槽底，逐层累计。',
    invariant: '栈内高度非递增。每次只累计本次新封闭的一层，不会把之前结算的水重复计入。',
    time: 'O(n)', space: 'O(n)', sample: { heights: [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1] },
    inputHint: 'heights：0–24 个整数，范围 0–100；不足三根柱子返回 0。', code: references['trapping-rain-water'],
  },
  {
    id: 'sliding-window-maximum', number: 239, title: '滑动窗口最大值', english: 'Sliding Window Maximum', category: '滑动窗口', difficulty: '困难', renderer: 'stack-window',
    summary: '固定长度 k 的窗口从左向右移动，按顺序返回每个完整窗口的最大值。',
    idea: '单调队列只保留可能成为最大值的下标：队首淘汰过期项，队尾淘汰不大于新值的项，队首即当前最大值。',
    invariant: '完成本轮入队后，下标递增、值严格递减且全部仍在窗口内；相等时保留更晚过期的位置。',
    time: 'O(n)', space: 'O(k) 不含结果', sample: { nums: [1, 3, -1, -3, 5, 3, 6, 7], k: 3 },
    inputHint: 'nums：1–24 个整数，范围 −10000–10000；k：1 到 nums.length 的整数。', code: references['sliding-window-maximum'],
  },
  {
    id: 'find-all-anagrams-in-a-string', number: 438, title: '找到字符串中所有字母异位词', english: 'Find All Anagrams in a String', category: '滑动窗口', difficulty: '中等', renderer: 'stack-window',
    summary: '返回 s 中与 p 长度相同、字符出现次数完全相同的所有子串起始下标，允许答案重叠。',
    idea: '维护一个长度为 p.length 的窗口，用缺失字符总数判断频次是否匹配，而不是只比较字符种类。',
    invariant: 'missing 等于目标字符尚缺的出现次数；窗口等长且 missing 为 0 时，频次才完全相等。',
    time: 'O(n + m)', space: 'O(Σ) 不含结果', sample: { s: 'cbaebabacd', p: 'abc' },
    inputHint: 's：0–32 个英文字母；p：1–12 个英文字母；区分大小写，下标从 0 开始。', code: references['find-all-anagrams-in-a-string'],
  },
  {
    id: 'minimum-window-substring', number: 76, title: '最小覆盖子串', english: 'Minimum Window Substring', category: '滑动窗口', difficulty: '困难', renderer: 'stack-window',
    summary: '找出 s 中包含 t 全部字符及其重复次数的最短连续子串；不存在或 t 为空时返回空字符串。',
    idea: '右端扩张直到覆盖目标，再尽量收缩左端。每次仍满足覆盖时记录更短窗口，重复这一过程。',
    invariant: '只有 missing 为 0 的窗口才可作为候选。相同长度不覆盖旧答案，因此保留最左边的最短窗口。',
    time: 'O(n + m)', space: 'O(Σ)', sample: { s: 'ADOBECODEBANC', t: 'ABC' },
    inputHint: 's：0–32 个英文字母；t：0–12 个英文字母；区分大小写；同长答案取最左侧。', code: references['minimum-window-substring'],
  },
  {
    id: 'longest-valid-parentheses', number: 32, title: '最长有效括号', english: 'Longest Valid Parentheses', category: '栈', difficulty: '困难', renderer: 'stack-window',
    summary: '只含圆括号的字符串中，求最长连续且完整匹配的括号子串长度，而不是不连续配对总数。',
    idea: '栈底保存最近一次无法匹配的右括号位置，初始为 −1。匹配弹栈后，用当前位置减栈顶位置得到有效连续段的长度。',
    invariant: '栈底是断点，其余项是未匹配左括号；有效段不能跨越断点。',
    time: 'O(n)', space: 'O(n)', sample: { s: ')()())' },
    inputHint: 's：0–32 个圆括号；空字符串返回 0；结果为字符长度。', code: references['longest-valid-parentheses'],
  },
  {
    id: 'decode-string', number: 394, title: '字符串解码', english: 'Decode String', category: '栈', difficulty: '中等', renderer: 'stack-window',
    summary: '将 k[片段] 展开为片段重复 k 次，允许嵌套和普通英文字母拼接。',
    idea: '进入括号时保存外层前缀与重复次数，闭合时把内层展开并拼回外层。每一层独立维护自己的片段。',
    invariant: '栈保存尚未闭合的外层上下文；当前片段只属于最内层，不会提前混入外层。',
    time: 'O(n × L)', space: 'O(n + L)', sample: { s: '3[a2[c]]' },
    inputHint: 's：最多 32 字符，仅英文字母、数字和 []；次数 1–20，最多嵌套 6 层，展开后不超过 120 字符；不允许空括号或游离数字。n 为编码长度，L 为展开长度。', code: references['decode-string'],
  },
];
